### ISSUE TITLE
Přístup zamítnut!

### ISSUE THREAD

**Issue by pokorj54** [fis-vse-discord/paul-bot#7]
Pro spuštění toho příkazu nemáš dostatečná oprávnění.
Pokud si myslíš, že jde o chybu, napiš někomu z moderátorů nebo otevři nové issue na Githubu

měl bych být schopen vidět svý credit score, jak jinak mám vědět, jestli můžu cestovat do zahraničí, nebo vědět zda mohu studovat na nějaké škole

**Comment by jirkavrba** [comment]
这是一个很好的观点，我们将尽快实施

**Comment by pokorj54** [comment]
非常感谢你!
